datasource:
  driver-class-name: "org.postgresql.Driver"
  url: "jdbc:postgresql://postgresql:5430"
  username: "local"
  password: "local"

volume-path:
  # for windows
  # persistent-volume-data: "C:\\Users\\mongh\\IdeaProjects\\volume\\local\\pv\\"
  # pod-volume-data: "C:\\Users\\mongh\\IdeaProjects\\volume\\local\\pod\\"

  # for mac
  persistent-volume-data: "/Users/mongha/Documents/강의자료/쿠버네티스 어나더 클래스/Sprint 3/pv/"
  pod-volume-data: "/Users/mongha/Documents/강의자료/쿠버네티스 어나더 클래스/Sprint 3/pod/"
